Disqus bug
guilherme-toti/nice-blog pull request #12
Opened 2018-02-07 13:07 UTC by somatheus

The last disqus code it was not working. It was giving a message 'We were unable to load disqus', so I made some researches I could know that one variable was deprecated, so I'm uploading the new code :D

2018-02-10 17:21 UTC, guilherme-toti requested changes

2018-02-10 17:21 UTC, guilherme-toti commented on templates/article.html
> -    <meta property="og:image" content="{{ article.image }}">
Why did you remove these `metas`?

2018-02-10 17:21 UTC, guilherme-toti commented on templates/article.html
> -	<section class="post-content">
I think this shouldn't be removed too

2018-02-10 17:21 UTC, guilherme-toti commented on templates/article.html
> +				</script>
The indentation here is not right

2018-02-10 17:21 UTC, guilherme-toti commented on templates/disqus_script.html
> +<noscript>Please enable JavaScript to view the</noscript>
This is necessary? I think it's not being call in any place

2019-06-29 18:01 UTC, 4s3ti commented
no activity since the review. and all seems to be working perfectly. 
Closing.

2019-06-29 18:01 UTC, closed without merging